image: maven:3.6-jdk-12-alpine

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn ${MAVEN_CLI_OPTS} compile

deploy_maven:
  stage: deploy
  only:
    - master
    variables:
      - $CI_COMMIT_MESSAGE =~ ^(?!\[maven-release-plugin\]).+
  before_script:
    - git remote set-url origin https://MrCraftCod:${CI_PUSH_TOKEN}@gitlab.com:MrCraftCod/JavaUtils.git
    - git config --global user.email 'zederr@gmail.com'
    - git config --global user.name 'Gitlab-CI'
  script:
    - mvn ${MAVEN_CLI_OPTS} release:clean release:prepare release:perform release:clean
