image: maven:3.6-jdk-12-alpine

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn ${MAVEN_CLI_OPTS} compile

deploy_maven:
  stage: deploy
  only:
    - master
  before_script:
    - chmod +x ./deploy-ci.sh
  script:
    - ./deploy-ci.sh
