image: maven:3.5.4-jdk-10-slim

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml -P MrCraftCod --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
  - .m2/repository/
  - target/

build:
  stage: build
  script:
  - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
  - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  script:
  - mvn $MAVEN_CLI_OPTS deploy
  only:
  - master