name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment-maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Publish with gradle
        uses: MrRamych/gradle-actions/openjdk-13@3.1
        with:
          args: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
